# Generated by Django 5.2.9 on 2025-12-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
        migrations.AddField(
            model_name='user',
            name='is_mydata_agreed',
            field=models.BooleanField(default=False, verbose_name='마이데이터 동의'),
        ),
        migrations.AddField(
            model_name='user',
            name='wealth',
            field=models.IntegerField(default=0, verbose_name='자산'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='연봉'),
        ),
    ]
