# Generated by Django 4.2.27 on 2025-12-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='search_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
